collection_name: collection_60_fields
fields:
  # String fields (12 fields with different null probabilities)
  - name: "1"
    type: string
    specs:
      length_range: [8, 20]
      null_probability: 0.0
  - name: "2"
    type: string
    specs:
      values: ["A", "B", "C", "D", "E"]
      null_probability: 0.0
  - name: "3"
    type: string
    specs:
      length_range: [5, 15]
      null_probability: 0.0
  - name: "4"
    type: string
    specs:
      length_range: [10, 30]
      null_probability: 0.3
  - name: "5"
    type: string
    specs:
      values: ["high", "medium", "low"]
      null_probability: 0.3
  - name: "6"
    type: string
    specs:
      length_range: [3, 12]
      null_probability: 0.3
  - name: "7"
    type: string
    specs:
      length_range: [15, 25]
      null_probability: 0.6
  - name: "8"
    type: string
    specs:
      values: ["north", "south", "east", "west"]
      null_probability: 0.6
  - name: "9"
    type: string
    specs:
      length_range: [20, 40]
      null_probability: 0.6
  - name: "10"
    type: string
    specs:
      length_range: [10, 50]
      null_probability: 0.9
  - name: "11"
    type: string
    specs:
      values: ["critical", "warning", "info", "debug"]
      null_probability: 0.9
  - name: "12"
    type: string
    specs:
      length_range: [1, 10]
      null_probability: 0.9

  # Big Integer fields (12 fields with different null probabilities)
  - name: "13"
    type: big_integer
    specs:
      range: [1000, 9999]
      null_probability: 0.0
  - name: "14"
    type: big_integer
    specs:
      values: [100, 200, 300, 400]
      null_probability: 0.0
  - name: "15"
    type: big_integer
    specs:
      range: [1, 100]
      null_probability: 0.0
  - name: "16"
    type: big_integer
    specs:
      range: [10000, 99999]
      null_probability: 0.3
  - name: "17"
    type: big_integer
    specs:
      values: [1000, 2000, 3000]
      null_probability: 0.3
  - name: "18"
    type: big_integer
    specs:
      range: [100, 999]
      null_probability: 0.3
  - name: "19"
    type: big_integer
    specs:
      range: [100000, 999999]
      null_probability: 0.6
  - name: "20"
    type: big_integer
    specs:
      values: [5, 10, 15, 20, 25]
      null_probability: 0.6
  - name: "21"
    type: big_integer
    specs:
      range: [1, 50]
      null_probability: 0.6
  - name: "22"
    type: big_integer
    specs:
      range: [1000000, 9999999]
      null_probability: 0.9
  - name: "23"
    type: big_integer
    specs:
      values: [1, 2, 3, 4, 5]
      null_probability: 0.9
  - name: "24"
    type: big_integer
    specs:
      range: [500, 1500]
      null_probability: 0.9

  # Big Decimal fields (12 fields with different null probabilities)
  - name: "25"
    type: big_decimal
    specs:
      range: [100.00, 999.99]
      precision: 2
      null_probability: 0.0
  - name: "26"
    type: big_decimal
    specs:
      values: [1.5, 2.5, 3.5, 4.5]
      precision: 1
      null_probability: 0.0
  - name: "27"
    type: big_decimal
    specs:
      range: [0.001, 0.999]
      precision: 3
      null_probability: 0.0
  - name: "28"
    type: big_decimal
    specs:
      range: [1000.00, 9999.99]
      precision: 2
      null_probability: 0.3
  - name: "29"
    type: big_decimal
    specs:
      values: [10.00, 20.00, 30.00]
      precision: 2
      null_probability: 0.3
  - name: "30"
    type: big_decimal
    specs:
      range: [1.00, 99.99]
      precision: 2
      null_probability: 0.3
  - name: "31"
    type: big_decimal
    specs:
      range: [100.000, 999.999]
      precision: 3
      null_probability: 0.6
  - name: "32"
    type: big_decimal
    specs:
      values: [0.5, 1.5, 2.5]
      precision: 1
      null_probability: 0.6
  - name: "33"
    type: big_decimal
    specs:
      range: [10000.00, 99999.99]
      precision: 2
      null_probability: 0.6
  - name: "34"
    type: big_decimal
    specs:
      range: [0.01, 9.99]
      precision: 2
      null_probability: 0.9
  - name: "35"
    type: big_decimal
    specs:
      values: [100.0, 200.0, 300.0]
      precision: 1
      null_probability: 0.9
  - name: "36"
    type: big_decimal
    specs:
      range: [1.000, 9.999]
      precision: 3
      null_probability: 0.9

  # Boolean fields (8 fields with different null probabilities)
  - name: "37"
    type: boolean
    specs:
      null_probability: 0.0
  - name: "38"
    type: boolean
    specs:
      null_probability: 0.0
  - name: "39"
    type: boolean
    specs:
      null_probability: 0.3
  - name: "40"
    type: boolean
    specs:
      null_probability: 0.3
  - name: "41"
    type: boolean
    specs:
      null_probability: 0.6
  - name: "42"
    type: boolean
    specs:
      null_probability: 0.6
  - name: "43"
    type: boolean
    specs:
      null_probability: 0.9
  - name: "44"
    type: boolean
    specs:
      null_probability: 0.9

  # Array fields (8 fields with different null probabilities)
  - name: "45"
    type: array
    specs:
      min_length: 1
      max_length: 5
      element_type: string
      element_specs:
        length_range: [3, 8]
      null_probability: 0.0
  - name: "46"
    type: array
    specs:
      min_length: 2
      max_length: 4
      element_type: big_integer
      element_specs:
        range: [1, 100]
      null_probability: 0.0
  - name: "47"
    type: array
    specs:
      min_length: 1
      max_length: 3
      element_type: boolean
      null_probability: 0.3
  - name: "48"
    type: array
    specs:
      min_length: 2
      max_length: 6
      element_type: big_decimal
      element_specs:
        range: [1.0, 100.0]
        precision: 1
      null_probability: 0.3
  - name: "49"
    type: array
    specs:
      min_length: 1
      max_length: 4
      element_type: string
      element_specs:
        values: ["small", "medium", "large"]
      null_probability: 0.6
  - name: "50"
    type: array
    specs:
      min_length: 2
      max_length: 5
      element_type: big_integer
      element_specs:
        values: [10, 20, 30, 40]
      null_probability: 0.6
  - name: "51"
    type: array
    specs:
      min_length: 1
      max_length: 3
      element_type: string
      element_specs:
        length_range: [5, 10]
      null_probability: 0.9
  - name: "52"
    type: array
    specs:
      min_length: 2
      max_length: 4
      element_type: boolean
      null_probability: 0.9

  # Datetime fields (8 fields with different null probabilities)
  - name: "53"
    type: datetime
    specs:
      range: ["2023-01-01T00:00:00Z", "2023-12-31T23:59:59Z"]
      null_probability: 0.0
  - name: "54"
    type: datetime
    specs:
      values: ["2023-03-01T12:00:00Z", "2023-06-01T12:00:00Z", "2023-09-01T12:00:00Z"]
      null_probability: 0.0
  - name: "55"
    type: datetime
    specs:
      range: ["2022-01-01T00:00:00Z", "2022-12-31T23:59:59Z"]
      null_probability: 0.3
  - name: "56"
    type: datetime
    specs:
      values: ["2024-01-01T00:00:00Z", "2024-06-01T00:00:00Z"]
      null_probability: 0.3
  - name: "57"
    type: datetime
    specs:
      range: ["2021-01-01T00:00:00Z", "2021-12-31T23:59:59Z"]
      null_probability: 0.6
  - name: "58"
    type: datetime
    specs:
      values: ["2025-01-01T12:00:00Z", "2025-07-01T12:00:00Z"]
      null_probability: 0.6
  - name: "59"
    type: datetime
    specs:
      range: ["2020-01-01T00:00:00Z", "2020-12-31T23:59:59Z"]
      null_probability: 0.9
  - name: "60"
    type: datetime
    specs:
      values: ["2026-01-01T00:00:00Z", "2026-12-31T23:59:59Z"]
      null_probability: 0.9